service: ampparit

provider:
  name: aws
  runtime: python2.7
  region: eu-west-1
  profile: heap
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:BatchWriteItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"
  environment:
    TABLE_NAME: ampparit

functions:
  fetcher:
    handler: fetcher.handler
    memorySize: 256
    events:
      - schedule: rate(15 minutes)
  apiGetItems:
    handler: api.get_items
    memorySize: 256
    events:
      - http: GET items
  apiGetItem:
    handler: api.get_item
    memorySize: 256
    events:
      - http: GET items/{id}

package:
  exclude:
    - "*.txt"
    - "*.md"
    - "*.json"
    - "client"
    - "node_modules"

resources:
  Resources:
    NewsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ampparit
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    WebAppS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.domainName}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    DomainName:
      Type: AWS::Route53::RecordSet
      Properties:
        #Name: ${self:custom.domainName}.
        Name: serverless.heap.fi.
        AliasTarget:
          DNSName: !Ref 
          HostedZoneId:
        Type: A
        HostedZoneId:

custom:
  domainName: serverless.heap.fi
